import {defaults,validateConfig,validQuad,cssMatrix,cropRect,clamp,clockState} from './mapping-core.mjs';
import {filmClips,filmLayersAt} from './film-cues.mjs';
import {createFilmSync} from './film-sync.mjs';
const $=id=>document.getElementById(id),show=window.D_SHOW,key='d-projection-mapping-v1',copy=x=>JSON.parse(JSON.stringify(x));
let config=defaults(),selected=0,drag=null,history=[],grid=false,present=false,demo=false,playing=false,time=show.events.heatOn+5,anchor=performance.now(),cue=null,cueAt=0,priority=-1;
try{const raw=localStorage.getItem(key);if(raw)config=validateConfig(JSON.parse(raw));}catch{}
let diskRevision=null,dirty=false,restoring=true;
const current=()=>config.regions[selected];
function remember(){history.push(copy(config));if(history.length>40)history.shift();$('undo').disabled=false;}
function save(){dirty=true;try{localStorage.setItem(key,JSON.stringify(config));$('save-status').textContent='已暫存於瀏覽器 · 請儲存為現場設定';}catch{$('save-status').textContent='無法自動儲存，請匯出備份';}}
const surfaces=config.regions.map((r,i)=>{const el=document.createElement('div'),canvas=document.createElement('canvas'),iframe=document.createElement('iframe');el.className='surface';iframe.src='mapping-ih.html';iframe.title='IH 爐投影來源';el.append(canvas,iframe);$('stage').append(el);return {el,canvas,ctx:canvas.getContext('2d'),iframe};});
const outlines=config.regions.map(()=>{const p=document.createElementNS('http://www.w3.org/2000/svg','polygon');p.setAttribute('fill','none');$('guides').append(p);return p;});
const tags=config.regions.map((r,i)=>{const b=document.createElement('button');b.className='tag';b.textContent=`0${i+1} ${r.name}`;b.onpointerdown=e=>start(e,i,-1);$('handles').append(b);return b;});
const handles=Array.from({length:4},(_,i)=>{const b=document.createElement('button');b.className='handle';b.setAttribute('aria-label',['左上角','右上角','右下角','左下角'][i]);b.innerHTML=`<span>${i+1}</span>`;b.onpointerdown=e=>start(e,selected,i);b.onkeydown=e=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();remember();const p=copy(current().points),n=e.shiftKey?10:1;p[i]=[clamp(p[i][0]+d[0]*n/innerWidth,0,1),clamp(p[i][1]+d[1]*n/innerHeight,0,1)];if(validQuad(p)){current().points=p;layout();save();}};$('handles').append(b);return b;});
const buttons=config.regions.map((r,i)=>{const b=document.createElement('button');b.className='region';b.innerHTML=`<b>0${i+1}</b><span>${r.name}</span>`;b.onclick=()=>select(i);$('regions').append(b);return b;});
function layout(){const w=innerWidth,h=innerHeight;$('guides').setAttribute('viewBox',`0 0 ${w} ${h}`);config.regions.forEach((r,i)=>{const s=surfaces[i],rw=r.resolution,rh=Math.round(rw/r.aspect);s.el.hidden=!r.enabled;Object.assign(s.el.style,{width:rw+'px',height:rh+'px',zIndex:r.layer,filter:`brightness(${r.brightness})`,transform:cssMatrix(r.points.map(([x,y])=>[x*w,y*h]),rw,rh)});if(s.canvas.width!==rw||s.canvas.height!==rh){s.canvas.width=rw;s.canvas.height=rh;}s.canvas.hidden=r.content==='ih'&&!grid;s.iframe.hidden=r.content!=='ih'||grid;const [cx,cy,cw]=cropRect(900,1400,r.aspect,r.zoom,r.panX,r.panY),scale=rw/cw;Object.assign(s.iframe.style,{width:'900px',height:'1400px',transform:`matrix(${r.mirror?-scale:scale},0,0,${scale},${r.mirror?rw+cx*scale:-cx*scale},${-cy*scale})`});outlines[i].setAttribute('points',r.points.map(([x,y])=>`${x*w},${y*h}`).join(' '));outlines[i].setAttribute('stroke',i===selected?'#bee8ce':'#668373');outlines[i].setAttribute('stroke-width',i===selected?'2':'1');outlines[i].setAttribute('stroke-dasharray',r.enabled?'':'5 5');tags[i].style.left=r.points[0][0]*w+'px';tags[i].style.top=Math.max(30,r.points[0][1]*h)+'px';tags[i].classList.toggle('active',i===selected);buttons[i].classList.toggle('active',i===selected);buttons[i].classList.toggle('off',!r.enabled);buttons[i].setAttribute('aria-pressed',i===selected);});handles.forEach((b,i)=>{b.style.left=current().points[i][0]*w+'px';b.style.top=current().points[i][1]*h+'px';});}
function select(i){selected=i;const r=current();$('region-name').textContent=r.name;for(const f of ['enabled','mirror'])$(f).checked=r[f];for(const f of ['content','aspect','resolution','zoom','panX','panY','brightness','lineWidth'])$(f).value=r[f];$('lineWidth-field').hidden=r.content!=='ih';labels();layout();}
function labels(){for(const f of ['zoom','panX','panY','brightness','lineWidth'])$(f+'-value').textContent=(f==='zoom'||f==='lineWidth')?current()[f].toFixed(2)+'×':Math.round(current()[f]*100)+'%';}
function start(e,i,corner){if(restoring||e.button!==0)return;e.preventDefault();select(i);remember();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);drag={id:e.pointerId,corner,x:e.clientX,y:e.clientY,points:copy(current().points)};}
window.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;let dx=(e.clientX-drag.x)/innerWidth,dy=(e.clientY-drag.y)/innerHeight,p=copy(drag.points);if(drag.corner<0){dx=clamp(dx,-Math.min(...p.map(a=>a[0])),1-Math.max(...p.map(a=>a[0])));dy=clamp(dy,-Math.min(...p.map(a=>a[1])),1-Math.max(...p.map(a=>a[1])));p=p.map(([x,y])=>[x+dx,y+dy]);}else{const i=drag.corner;p[i]=[clamp(p[i][0]+dx,0,1),clamp(p[i][1]+dy,0,1)];}if(validQuad(p)){current().points=p;layout();}});
for(const event of ['pointerup','pointercancel'])window.addEventListener(event,()=>{if(drag){drag=null;save();}});
for(const f of ['enabled','mirror','content','aspect','resolution'])$(f).onchange=()=>{remember();current()[f]=['enabled','mirror'].includes(f)?$(f).checked:f==='content'?$(f).value:Number($(f).value);if(f==='content')Object.assign(current(),{aspect:current().content==='ih'?9/14:16/9,zoom:1,panX:.5,panY:.5});select(selected);save();};
for(const f of ['zoom','panX','panY','brightness','lineWidth']){$(f).onpointerdown=remember;$(f).onkeydown=e=>{if(e.key.startsWith('Arrow'))remember();};$(f).oninput=()=>{current()[f]=Number($(f).value);labels();layout();save();};}
$('grid').onchange=()=>{grid=$('grid').checked;layout();};$('reset-corners').onclick=()=>{remember();current().points=defaults().regions[selected].points;layout();save();};$('reset-crop').onclick=()=>{remember();Object.assign(current(),{aspect:current().content==='ih'?9/14:16/9,zoom:1,panX:.5,panY:.5});select(selected);save();};
for(const [id,top]of [['front',true],['back',false]])$(id).onclick=()=>{remember();const order=config.regions.map((r,i)=>i).sort((a,b)=>config.regions[a].layer-config.regions[b].layer).filter(i=>i!==selected);top?order.push(selected):order.unshift(selected);order.forEach((i,n)=>config.regions[i].layer=n);layout();save();};
$('undo').disabled=true;$('undo').onclick=()=>{if(!history.length)return;config=history.pop();select(selected);save();$('undo').disabled=!history.length;};
for(const [id,crop]of [['warp-tab',false],['crop-tab',true]])$(id).onclick=()=>{$('warp-panel').hidden=crop;$('crop-panel').hidden=!crop;$('warp-tab').setAttribute('aria-pressed',!crop);$('crop-tab').setAttribute('aria-pressed',crop);};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='D區-投影校正.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>65536)throw Error('檔案太大');const next=validateConfig(JSON.parse(await f.text()));remember();config=next;select(selected);save();}catch(e){$('save-status').textContent='匯入失敗：'+e.message;}$('file').value='';};
function output(value){present=value;document.body.classList.toggle('present',value);if(value){grid=false;$('grid').checked=false;layout();}}
$('present').onclick=async()=>{output(true);try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();}catch{output(false);$('save-status').textContent='請先使用瀏覽器全螢幕，再按 F 隱藏控制介面。';}};
$('blackout').onclick=()=>{const b=document.body.classList.toggle('blackout');$('blackout').textContent=b?'解除黑場':'黑場';};document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)output(false);layout();});
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();$('undo').click();return;}if(k==='f')output(!present);if(k==='p')$('present').click();if(k==='b')$('blackout').click();if(k==='escape')output(false);if(/^[1-4]$/.test(k))select(Number(k)-1);});window.addEventListener('resize',layout);
const master=document.createElement('canvas');master.width=1920;master.height=1080;const ctx=master.getContext('2d',{alpha:false});
const players=Object.fromEntries(Object.entries(filmClips).map(([id,clip])=>{const v=document.createElement('video');v.playsInline=true;v.muted=true;v.src=clip.file;return [id,{v,control:createFilmSync(v),id:null,corrected:0}];}));
function accept(s){if(!s||!Number.isFinite(s.time)||typeof s.playing!=='boolean')return;if(s.priority!=null&&s.priority<priority&&performance.now()-cueAt<4000)return;cue=s;cueAt=performance.now();priority=s.priority??0;}
const query=new URLSearchParams(location.search),endpoint=query.get('sync')||(location.port==='8776'?'/api/state':null);
if(endpoint){(async function poll(){try{const r=await fetch(endpoint,{cache:'no-store',signal:AbortSignal.timeout(1800)});if(r.ok)accept(await r.json());}catch{}setTimeout(poll,250);})();}else{const bus=new BroadcastChannel('dweb-exhibit-cue');bus.onmessage=e=>{if(e.data?.source==='preview-clock')accept(e.data);};bus.postMessage({request:'cue'});}
const demoTime=()=>clamp(time+(playing?(performance.now()-anchor)/1000:0),0,show.duration);
$('source').onchange=()=>{demo=$('source').value==='demo';$('demo-controls').hidden=!demo;anchor=performance.now();};$('play').onclick=()=>{time=demoTime();if(time>=show.duration)time=0;anchor=performance.now();playing=!playing;for(const p of Object.values(players))p.control.unlock();};
const sceneTimes=[show.events.heatOn+5,show.events.exhaustOn+2,show.events.freshOn+5,show.events.heatOff+4];Array.from($('scene').options).forEach((o,i)=>o.value=sceneTimes[i]);$('scene').onchange=()=>{time=Number($('scene').value);anchor=performance.now();};$('timeline').max=show.duration;$('timeline').oninput=()=>{time=Number($('timeline').value);anchor=performance.now();};
function drawGrid(c,w,h,i){c.fillStyle='#07100b';c.fillRect(0,0,w,h);c.strokeStyle='#5c8c6c';c.lineWidth=2;c.beginPath();for(let n=0;n<=8;n++){c.moveTo(n*w/8,0);c.lineTo(n*w/8,h);c.moveTo(0,n*h/8);c.lineTo(w,n*h/8);}c.stroke();c.strokeStyle='#d8f7e2';c.lineWidth=5;c.strokeRect(3,3,w-6,h-6);c.beginPath();c.arc(w/2,h/2,Math.min(w,h)*.2,0,Math.PI*2);c.stroke();c.fillStyle='#d8f7e2';c.textAlign='center';c.font=`${Math.min(w,h)*.12}px sans-serif`;c.fillText('0'+(i+1),w/2,h*.54);}
const fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
let last=0,lastUI=0;
function frame(now){requestAnimationFrame(frame);if(now-last<30)return;last=now;const state=demo?{connected:true,time:demoTime(),playing}:clockState(cue,(now-cueAt)/1000,show.duration);if(demo&&state.time>=show.duration){playing=false;time=show.duration;state.playing=false;}const layers=state.connected?filmLayersAt(show,state.time):[];let loading=false,failed=false;
for(const [id,p]of Object.entries(players)){const l=layers.find(l=>l.clip===id);if(l){if(p.id!==l.id){p.id=l.id;p.control.seek(l.localTime);}p.v.playbackRate=l.rate;if(!p.v.seeking&&p.v.readyState>=2&&now-p.corrected>1500&&Math.abs(p.v.currentTime-Math.min(l.localTime,p.v.duration-.05))>.45){p.control.seek(l.localTime);p.corrected=now;}p.control.sync(l.localTime,state.playing,now);loading ||= p.v.readyState<2;failed ||= !!p.v.error;}else{p.control.sync(p.v.currentTime,false,now);p.id=null;}}
ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;ctx.fillStyle='#000';ctx.fillRect(0,0,1920,1080);ctx.globalCompositeOperation='lighter';for(const l of layers){const v=players[l.clip].v;if(v.readyState>=2){ctx.globalAlpha=l.weight*(l.clip==='green'?1:.52);ctx.drawImage(v,0,0,1920,1080);}}ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';
config.regions.forEach((r,i)=>{if(!r.enabled)return;const s=surfaces[i],w=s.canvas.width,h=s.canvas.height;if(grid&&!present){drawGrid(s.ctx,w,h,i);return;}if(r.content!=='smoke')return;s.ctx.save();s.ctx.fillStyle='#000';s.ctx.fillRect(0,0,w,h);if(r.mirror){s.ctx.translate(w,0);s.ctx.scale(-1,1);}s.ctx.drawImage(master,...cropRect(1920,1080,r.aspect,r.zoom,r.panX,r.panY),0,0,w,h);s.ctx.restore();});
if(!present&&!$('crop-panel').hidden){const c=$('crop-preview').getContext('2d'),r=current();c.fillStyle='#000';c.fillRect(0,0,480,270);if(r.content==='smoke'){c.drawImage(master,0,0,480,270);const [x,y,w,h]=cropRect(1920,1080,r.aspect,r.zoom,r.panX,r.panY);c.strokeStyle='#d1f5df';c.lineWidth=2;c.strokeRect(x/4,y/4,w/4,h/4);}else{c.fillStyle='#b5cfc0';c.font='16px sans-serif';c.textAlign='center';c.fillText('IH 裁切直接顯示在投影區',240,135);}}
if(now-lastUI>150){lastUI=now;for(const [i,s] of surfaces.entries())s.iframe.contentWindow?.postMessage({type:'d-mapping-cue',lineWidth:config.regions[i].lineWidth,cue:state.connected?{time:state.time,playing:state.playing}:null},location.origin);$('connection').textContent=failed?'影片載入失敗':loading?'影片載入中':demo?'本頁預覽':state.connected?'● 已同步 D 區':'○ 等待 D 區同步';$('time').textContent=fmt(state.time)+' / '+fmt(show.duration);$('play').textContent=playing?'暫停':'播放';if(document.activeElement!==$('timeline'))$('timeline').value=state.time;}}
select(0);if(query.get('output')==='1')output(true);requestAnimationFrame(frame);

// Durable installation profile is explicitly committed, separate from local drafts.
$('save-install').onclick=async()=>{if(restoring)return;const button=$('save-install');button.disabled=true;const savedConfig=JSON.stringify(config);try{const r=await fetch('/api/mapping/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:diskRevision,config}),signal:AbortSignal.timeout(5000)});const d=await r.json();if(!r.ok)throw Error(d.error||'儲存失敗');diskRevision=d.revision;dirty=JSON.stringify(config)!==savedConfig;$('save-status').textContent=dirty?'較早的調整已存入 · 最新調整請再次儲存':'已存入此電腦 · 下次開啟自動恢復';}catch(e){$('save-status').textContent='尚未存入電腦：'+e.message+'。請先匯出備份。';}finally{button.disabled=false;}};
async function restoreInstallation(){try{const r=await fetch('/api/mapping/config',{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw Error('unavailable');const d=await r.json();diskRevision=d.revision;if(d.config&&!dirty){config=validateConfig(d.config);select(selected);localStorage.setItem(key,JSON.stringify(config));$('save-status').textContent=d.recovered?'已從備份恢復 · 請重新儲存現場設定':'已載入此電腦的現場設定';}else if(!d.config)$('save-status').textContent='尚無現場設定 · 校正後請按儲存';}catch{$('save-status').textContent='目前僅瀏覽器暫存 · 現場儲存服務未連線';}finally{restoring=false;}}
restoreInstallation();
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
