"""Create a compact Pages soundtrack, retaining the PCM master as fallback."""
import argparse, hashlib, json, os, shutil, subprocess
from pathlib import Path

def build_web_audio(root, show, ffmpeg=None):
    encoder = ffmpeg or os.environ.get('FFMPEG_BINARY') or shutil.which('ffmpeg')
    if not encoder:
        return False  # Standard-library builds still publish their fresh WAV.
    source = root / show.get('audioFallback', show['audio'])
    output = source.with_suffix('.mp3')
    subprocess.run([encoder, '-hide_banner', '-loglevel', 'error', '-y', '-i', str(source),
                    '-c:a', 'libmp3lame', '-b:a', '96k', str(output)], check=True)
    show['audioFallback'] = source.relative_to(root).as_posix()
    version = hashlib.sha256(output.read_bytes()).hexdigest()[:10]
    show['audio'] = output.relative_to(root).as_posix() + '?v=' + version
    return True

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--ffmpeg')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    show = json.loads((root / 'show.json').read_text(encoding='utf-8'))
    if not build_web_audio(root, show, args.ffmpeg):
        raise SystemExit('Set FFMPEG_BINARY or pass --ffmpeg to export web audio.')
    data = json.dumps(show, ensure_ascii=False, indent=2)
    (root / 'show.json').write_text(data + '\n', encoding='utf-8')
    (root / 'show-config.js').write_text('// Generated by tools/build_voice_show.py\nwindow.D_SHOW = ' + data + ';\n', encoding='utf-8')
