"""Build the shared show clock, captions and one seekable PCM soundtrack.

Run after all VoAI WAV exports are placed in assets/audio. No playback occurs.
"""
import json, wave, array, sys
from pathlib import Path
from build_soundtrack import build_mix
from build_web_audio import build_web_audio

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = json.loads((ROOT / 'voice-script.json').read_text(encoding='utf-8'))
RATE = 32000

def read_clip(clip):
    path = ROOT / 'assets/audio' / (clip['id'] + '.wav')
    with wave.open(str(path), 'rb') as src:
        if (src.getnchannels(), src.getsampwidth(), src.getframerate()) != (1, 2, RATE):
            raise ValueError(f'{path.name}: expected mono PCM16 at {RATE}Hz')
        samples = array.array('h', src.readframes(src.getnframes()))
    if sys.byteorder != 'little': samples.byteswap()
    if not samples or max(map(abs, samples)) < 100:
        raise ValueError(f'{path.name}: empty or silent recording')
    return samples

def build():
    clips = [{**c, 'samples': read_clip(c)} for c in SCRIPT['clips']]
    starts, cursor, output = [], 0., []
    for scene in range(1, 7):
        starts.append(cursor)
        at = cursor + (.75 if scene == 1 else .25)
        for c in [c for c in clips if c['scene'] == scene]:
            duration = len(c['samples']) / RATE
            output.append({k:v for k,v in c.items() if k != 'samples'} | {
                'start': round(at, 3), 'end': round(at+duration, 3),
                'file': f"assets/audio/{c['id']}.wav"})
            at += duration + .45
        # Move on after speech, rather than padding each scene to an old minimum.
        cursor = round(output[-1]['end'] + (3.3 if scene == 4 else .25 if scene < 6 else 3.5), 3)
    by_id = {c['id']:c for c in output}
    show = {'version': SCRIPT['version'], 'duration': cursor, 'starts': starts,
            'events': {'heatOn': by_id['d03-mother']['end'],
                       'heatOff': by_id['d06-mother']['end'],
                       'exhaustOn': round(by_id['d04-alert']['end'] + .3, 3),
                       'freshOn': starts[4]},
            'audio': 'assets/audio/theatre-voice.wav', 'clips': output}
    show['closingStart'] = round(by_id['d06-narrator']['end'] + .5, 3)
    show['exhaustMode'] = 'manual-demonstration-after-alert'
    if 'd00-intro' in by_id:
        show['intro'] = {k:by_id['d00-intro'][k] for k in ('start','end','text')}
        show['intro']['bodyStart'] = by_id['d00-intro']['end'] + .225
    mix = array.array('h', [0]) * round(cursor * RATE)
    for c, cue in zip(clips, output):
        offset = round(cue['start'] * RATE)
        # Keep original timbre and comfortable headroom; never amplify peaks.
        peak = max(map(abs, c['samples']))
        gain = min(1., 27500/peak)
        samples = array.array('h', (round(s*gain) for s in c['samples']))
        mix[offset:offset+len(samples)] = samples
    if sys.byteorder != 'little': mix.byteswap()
    with wave.open(str(ROOT / show['audio']), 'wb') as dst:
        dst.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
        dst.writeframes(mix.tobytes())
    build_mix(ROOT, show, RATE)
    build_web_audio(ROOT, show)
    data = json.dumps(show, ensure_ascii=False, indent=2)
    (ROOT/'show.json').write_text(data+'\n', encoding='utf-8')
    (ROOT/'show-config.js').write_text('// Generated by tools/build_voice_show.py\nwindow.D_SHOW = '+data+';\n', encoding='utf-8')
    def stamp(t):
        ms=round(t*1000); return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02}.{ms%1000:03}'
    vtt='WEBVTT\n\n'+'\n\n'.join(f"{c['id']}\n{stamp(c['start'])} --> {stamp(c['end'])}\n{c['role']}：{c['text']}" for c in output)
    (ROOT/'assets/audio/theatre-voice.vtt').write_text(vtt+'\n', encoding='utf-8')
    print(f"Built {len(output)} cues, {cursor:g}s. IH: {show['events']}")

if __name__ == '__main__': build()
