import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {ihState} from '../ih-simple-state.mjs';
const scope={window:{}};vm.runInNewContext(fs.readFileSync(new URL('../show-config.js',import.meta.url),'utf8'),scope);
const show=scope.window.D_SHOW,{heatOn,heatOff}=show.events;
const state=(time,playing=false,age=0)=>ihState({time,playing},age,show);
assert.equal(state(heatOn-.01).on,false);
assert.equal(state(heatOn).on,true);
assert.equal(state(heatOff-.01).on,true);
assert.equal(state(heatOff).on,false);
assert.equal(state(heatOn,false,3).on,true);
assert.equal(state(heatOn,false,4).on,false);
assert.equal(state(heatOff-1,true,2).on,false);
assert.equal(state(show.duration,true,1).on,false);
assert.equal(ihState(null,0,show).on,false);
assert.equal(ihState(null,0,show,'on').on,true);
assert.equal(ihState({time:heatOn,playing:true},0,{events:{}}).on,false);
console.log('IH boundary, pause, stale sync and end-of-show checks passed.');
